<<<<<<< HEAD
baseURL = "https://leopardshadow.github.io"
#baseURL = "https://cchenglo.com"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "zh-tw"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# number of post in a page
paginate = 10
canonifyurls = true

# code highlight
pygmentsstyle = "perldoc"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
#
# disqusShortname = "leopardshadow"
#
# googleAnalytics = "UA-167530869-1"



[params]

  hostName = "blog.cchenglo.com"

  # LoveIt theme version
  version = "0.2.X"
  footercontent = "."

  # [params.app]
  # # optional site title override for the app when added to an iOS home screen or Android launcher
  # title = "LoveIt"
  # # whether to omit favicon resource links
  # noFavicon = false
  # # modern SVG favicon to use in place of older style .png and .ico files
  # svgFavicon = ""
  # # Android browser theme color
  # themeColor = "#ffffff"
  # # Safari mask icon color
  # iconColor = "#5bbad5"
  # # Windows v8-10 tile color
  # tileColor = "#da532c"

  likerID = "chenglo"

  #  Search config
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    #  max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 30
    #  HTML tag name of the highlight part in results
    highlightTag = "em"
    #  whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

    # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    #  Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "CCLo's Notes"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      #  whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    #  Custom content (HTML format is supported)
    custom = '+x'
    #  whether to show Hugo and theme info
    hugo = true
    #  whether to show copyright info
    copyright = true
    #  whether to show the author
    author = true
    # Site creation time
    since = 2017
    # # ICP info only in China (HTML format is supported)
    # icp = ""
    # # license info (HTML format is supported)
    # license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


  #  Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  #  List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    #  amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "images/leopardshadow.png"
      #  title shown in home page (HTML format is supported)
      title = "blog :: String -> World -> World"
      # subtitle shown in home page
      subtitle = ""
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      #  disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 6
      #  replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false




  # Social links
  [params.social]
    Github = "leopardshadow"
    Facebook = "cchenglo"
    Instagram = "cchenglo"
    Medium = "cchenglo"
      # Matters = "@cchenglo"



  #  Page config
  [params.page]
    #  whether to hide a page from home page
    hiddenFromHomePage = false
    #  whether to hide a page from search results
    hiddenFromSearch = false
    #  whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    #  whether to enable the ruby extended syntax
    ruby = true
    #  whether to enable the fraction extended syntax
    fraction = true
    #  whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    #  whether to show the full text content in RSS
    rssFullText = false
    #  Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      #  whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    #  KaTeX mathematical formulas
    [params.page.math]
      enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
    #  Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    #  Mapbox GL JS config
    [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = ""
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # whether to add NavigationControl
      navigation = true
      # whether to add GeolocateControl
      geolocate = true
      # whether to add ScaleControl
      scale = true
      # whether to add FullscreenControl
      fullscreen = true
    #  social share links in post page
    [params.page.share]
      enable = false
      Twitter = false
      Facebook = false
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

    #  Comment config
    [params.page.comment]
      enable = true
      # Disqus comment config
      [params.page.comment.disqus]
        #
        enable = true
        # Disqus shortname to use Disqus in posts
        shortname = "leopardshadow"
      # Gitalk comment config
      [params.page.comment.gitalk]
        #
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine comment config
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        #  emoji data file name, default is "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # located in "themes/LoveIt/assets/data/emoji/" directory
        # you can store your own data files in the same path under your project:
        # "assets/data/emoji/"
        emoji = ""
      # Facebook comment config
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      #  Telegram comments config
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      #  Commento comment config
      [params.page.comment.commento]
        enable = false
      #  Utterances comment config
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"



        #  Third-party library config
        [params.page.library]
          [params.page.library.css]
            # someCSS = "some.css"
            # located in "assets/"
            # Or
            # someCSS = "https://cdn.example.com/some.css"
          [params.page.library.js]
            # someJavascript = "some.js"
            # located in "assets/"
            # Or
            # someJavascript = "https://cdn.example.com/some.js"
        #  SEO config
        [params.page.seo]
          # Publisher info
          [params.page.seo.publisher]
            name = "xxxx"
            [params.page.seo.publisher.logo]
              url = ""
              width = 127
              height = 40
          # Logo info
          [params.page.seo.logo]
            url = ""
            width = 127
            height = 40
          # Image info
          [params.page.seo.image]
            url = ""
            width = 800
            height = 600

      #  TypeIt config
      [params.typeit]
        # typing speed between each step (measured in milliseconds)
        speed = 100
        # blinking speed of the cursor (measured in milliseconds)
        cursorSpeed = 1000
        # character used for the cursor (HTML format is supported)
        cursorChar = "|"
        # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
        duration = -1

      # Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
      [params.verification]
        google = ""
        bing = ""
        yandex = ""
        pinterest = ""
        baidu = ""

      #  Analytics config
      [params.analytics]
        enable = true
        # Google Analytics
        [params.analytics.google]
          id = "UA-167530869-1"
          # whether to anonymize IP
          anonymizeIP = true
        # Fathom Analytics
        [params.analytics.fathom]
          id = ""
          # server url for your tracker if you're self hosting
          server = ""

      #  Cookie consent config
      [params.cookieconsent]
        enable = false
        # text strings used for Cookie consent banner
        [params.cookieconsent.content]
          message = ""
          dismiss = ""
          link = ""

      #  CDN config for third-party library files
      [params.cdn]
        # CDN data file name, disabled by default
        # ("jsdelivr.yml")
        # located in "themes/LoveIt/assets/data/cdn/" directory
        # you can store your own data files in the same path under your project:
        # "assets/data/cdn/"
        data = ""

      #  Compatibility config
      [params.compatibility]
        # whether to use Polyfill.io to be compatible with older browsers
        polyfill = false
        # whether to use object-fit-images to be compatible with older browsers
        objectFit = false

    # Markup related config in Hugo
    [markup]
      # Syntax Highlighting
      [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        # false is a necessary configuration
        # (https://github.com/dillonzq/LoveIt/issues/158)
        noClasses = false
      # Goldmark is from Hugo 0.60 the default library used for Markdown
      [markup.goldmark]
        [markup.goldmark.extensions]
          definitionList = true
          footnote = true
          linkify = true
          strikethrough = true
          table = true
          taskList = true
          typographer = true
        [markup.goldmark.renderer]
          # whether to use HTML tags directly in the document
          unsafe = true
      # Table Of Contents settings
      [markup.tableOfContents]
        startLevel = 2
        endLevel = 3

    # Author config
    [author]
      name = "cchenglo"
      email = ""
      link = ""

    # Sitemap config
    [sitemap]
      changefreq = "weekly"
      filename = "sitemap.xml"
      priority = 0.5

    # Permalinks config
    [Permalinks]
      # posts = ":year/:month/:filename"
      posts = ":filename"

    # Privacy config
    [privacy]
      #  privacy of the Google Analytics (replaced by params.analytics.google)
      [privacy.googleAnalytics]
        # ...
      [privacy.twitter]
        enableDNT = true
      [privacy.youtube]
        privacyEnhanced = true

    # Options to make output .md files
    [mediaTypes]
      [mediaTypes."text/plain"]
        suffixes = ["md"]

    # Options to make output .md files
    [outputFormats.MarkDown]
      mediaType = "text/plain"
      isPlainText = true
      isHTML = false

    # Options to make hugo output files
    [outputs]
      #
      home = ["HTML", "RSS", "JSON"]
      page = ["HTML", "MarkDown"]
      section = ["HTML", "RSS"]
      taxonomy = ["HTML", "RSS"]
      taxonomyTerm = ["HTML"]






[menu]
  [[menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      weight = 1
      url  = "/posts/"
  # [[menu.main]]
  #     identifier = "life"
  #     name = "生活"
  #     weight = 2
  #     url  = "/life/"
  [[menu.main]]
      identifier = "about"
      name = "關於"
      weight = 3
      url = "/about/"
  [[menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "標籤"
      url = "/tags/"
      title = ""
      weight = 4
  # [[menu.main]]
  #     identifier = "categories"
  #     pre = ""
  #     post = ""
  #     name = "分類"
  #     url = "/categories/"
  #     title = ""
  #     weight = 5
=======
baseurl = "/"
title = "cchenglo"
languageCode = "zh-tw"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Cheng-Cheng Lo"
  bio = "NCTU student,"
  # avatar = "img/avatar.png"

[Params]
  subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "Cheng-Cheng Lo's personal blog." # Site description. Used in meta description
  copyright = "Cheng-Cheng Lo" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["posts", "blog", "news", "life"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#fd8232" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/placeholder.png" # Logo image. Path relative to "static"
  title = "Cheng-Cheng Lo" # Logo title, otherwise will use site title
  subtitle = "my personal blog" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "username"
  twitter = "username"
  instagram = "username"
  linkedin = "username"
  telegram = "username"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  email = "example@example.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://youtube.com/user/username"

# [[Params.widgets.social.custom]]
#   title = "My Home Page"
#   url = "http://example.com"


>>>>>>> update blog
